migrate to jHipster 6.5.1
xm-online/tmf-ms-promotion pull request #8
Opened 2019-12-27 14:17 UTC by yevheniimuzyka

2019-12-30 13:19 UTC, v-kyrychenko requested changes

2019-12-30 13:19 UTC, v-kyrychenko commented on src/test/resources/config/application.yml
>              hibernate.hbm2ddl.auto: validate
next exception was found in test logs:
`Caused by: org.apache.http.conn.HttpHostConnectException: Connect to localhost:8500 [localhost/127.0.0.1] failed: Connection refused (Connection refused)`

this error should be removed, (5.6 section in the migration document)

2019-12-30 13:41 UTC, v-kyrychenko submitted a review, later dismissed

2020-01-02 10:31 UTC, vkirichenko commented on gradle/swagger.gradle
>      validateSpec = true
this file not applyed in main build.gradle

2020-01-02 10:50 UTC, vkirichenko commented on src/main/resources/config/application-dev.yml
> +        contexts: dev, faker
please check dev profile
`Failed to load driver class org.h2.Driver`

2020-01-02 12:19 UTC, v-kyrychenko approved these changes

2020-01-16 09:01 UTC, amedvedchuk approved these changes

2020-02-13 14:18 UTC, merged